# -*- coding: utf-8 -*-
"""WEB SCRAPPING: booktoscrape.com

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jQMAeWybDvq7P34IdayvaPS_vrBB-uaI
"""

#library:
from bs4 import BeautifulSoup
import requests
import pandas as pd

# The webpage URL
data=[]
for j in range(1,3):
  URL = f"https://books.toscrape.com/catalogue/category/books/mystery_3/page-{j}.html"
  webpage = requests.get(URL)
  webpage = webpage.content
  soup = BeautifulSoup(webpage, 'html.parser')
  book= soup.find('ol',class_='row')
  article= book.find_all('article', class_='product_pod')

  for i in article:
    link='https://books.toscrape.com/catalogue'+ i.find('a')['href'][8:]

    title= i.find('div',class_='image_container').img.attrs['alt']

    rating= i.find('p').attrs.get('class')[1]

    price=i.find('p',class_='price_color').text

    data.append({'Title': title,'Link': link,'Price': price, 'Rating': rating})

df = pd.DataFrame(data)
df

